# Generated by Django 3.1.1 on 2020-09-27 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_enrollment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='slug',
        ),
    ]
